name: PHP Composer on Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # Thiết lập PHP trên Windows
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0' # Bạn có thể đổi sang phiên bản PHP khác
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate --strict
        # Trên Windows runner, composer đã có sẵn khi dùng setup-php.
        # Nếu bạn gặp lỗi lệnh bash không tồn tại, bạn có thể bỏ shell: bash hoặc dùng PowerShell:
        # shell: pwsh

      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
        # shell: pwsh
        # Nếu cần, bạn có thể chỉ định shell PowerShell hoặc cmd:
        # shell: cmd

      # Nếu bạn có script test trong composer.json (ví dụ "test": "vendor/bin/phpunit")
      # - name: Run test suite
      #   run: composer run-script test
